apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-consumer
  labels:
    app: consumer
  namespace: inicial-zair-bulos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: zairbulos/295k8s-consumer
        env:
          - name: SERVICE_URL
            value: "http://service-flask-app"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"