apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-flask
  labels:
    app: flask
  namespace: inicial-zair-bulos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: zairbulos/295k8s-flask
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000