apiVersion: v1
kind: Service
metadata:
  name: service-flask-app
  namespace: inicial-zair-bulos
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000