name: CI/CD
on:
  workflow_dispatch:
  push:
    paths:
      - 'wanderlust/**'
env:
  NODE_VERSION: 21
  REGISTRY: zairbulos
  REPOSITORY: 295wanderlust
  VERSION: v1.0.0
jobs:
  # Backend CI
  ci-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wanderlust/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  
  # Backend CD
  cd-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wanderlust/backend
    needs: ci-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.3.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Docker Build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:backend-${{ env.VERSION }} .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:backend-${{ env.VERSION }}

  # Frontend CI
  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wanderlust/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install

  # Frontend CD
  cd-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wanderlust/frontend
    needs: [ci-frontend, cd-backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.3.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Docker Build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:frontend-${{ env.VERSION }} .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:frontend-${{ env.VERSION }}